import { loadCompositeProjection, registerProjection } from '@atlas-composer/projection-loader'
import { geoConicConformal, geoMercator } from 'd3-geo'
/**
 * Composite Projection for France
 * Generated by Atlas composer v1.0
 * Export date: 17/10/2025
 *
 * Pattern: single-focus
 * Territories: France Métropolitaine, Guadeloupe, Martinique, Guyane, La Réunion, Mayotte, Saint-Martin, Saint-Pierre-et-Miquelon, Wallis-et-Futuna, Polynésie française, Polynésie française (îles éloignées), Nouvelle-Calédonie, Terres australes et antarctiques françaises
 * Language: JavaScript
 */
import { config } from './projection-preset'

export function createFranceProjection() {
  // Step 1: Register projections used in this configuration
  // The standalone projection loader requires projections to be registered
  // before loading a composite configuration.
  registerProjection('conic-conformal', () => geoConicConformal())
  registerProjection('mercator', () => geoMercator())

  // Step 3: Load the composite projection
  // Specify the target dimensions for the projection
  // Adjust width and height as needed for your use case
  const projection = loadCompositeProjection(config, {
    width: 960,
    height: 500,
    debug: true,
  })

  return projection
}
