/**
 * Composite Projection for France
 * Generated by Atlas composer v1.0
 * Export date: 17/10/2025
 *
 * Pattern: single-focus
 * Territories: France Métropolitaine, Guadeloupe, Martinique, Guyane, La Réunion, Mayotte, Saint-Martin, Saint-Pierre-et-Miquelon, Wallis-et-Futuna, Polynésie française, Polynésie française (îles éloignées), Nouvelle-Calédonie, Terres australes et antarctiques françaises
 * Language: JavaScript
 */

import { loadCompositeProjection, registerProjection } from '@atlas-composer/projection-loader'
import { geoConicConformal, geoMercator } from 'd3-geo'

export function createFranceProjection() {
  // Step 1: Register projections used in this configuration
  // The standalone projection loader requires projections to be registered
  // before loading a composite configuration.
  registerProjection('conic-conformal', () => geoConicConformal())
  registerProjection('mercator', () => geoMercator())

  // Step 2: Define the composite projection configuration
  // This configuration was exported from Atlas composer
  const config = {
    version: '1.0',
    metadata: {
      atlasId: 'france',
      atlasName: 'France',
      exportDate: '2025-10-17T00:26:37.784Z',
      createdWith: 'Atlas composer v1.0',
    },
    pattern: 'single-focus',
    referenceScale: 2700,
    canvasDimensions: {
      width: 960,
      height: 500,
    },
    territories: [
      {
        code: 'FR-MET',
        name: 'France Métropolitaine',
        role: 'primary',
        projection: {
          id: 'conic-conformal',
          family: 'CONIC',
          parameters: {
            rotate: [
              -3,
              -46.2,
              0,
            ],
            parallels: [
              0,
              60,
            ],
            scaleMultiplier: 1,
          },
        },
        layout: {
          translateOffset: [
            0,
            0,
          ],
          clipExtent: null,
        },
        bounds: [
          [
            -6.5,
            41,
          ],
          [
            10,
            51,
          ],
        ],
      },
      {
        code: 'FR-GP',
        name: 'Guadeloupe',
        role: 'secondary',
        projection: {
          id: 'mercator',
          family: 'CYLINDRICAL',
          parameters: {
            center: [
              -61.46,
              16.14,
            ],
            scaleMultiplier: 1.4,
          },
        },
        layout: {
          translateOffset: [
            -324,
            -38,
          ],
          clipExtent: [
            [
              -0.14,
              -0.032,
            ],
            [
              -0.0996,
              0,
            ],
          ],
        },
        bounds: [
          [
            -61.81,
            15.83,
          ],
          [
            -61,
            16.52,
          ],
        ],
      },
      {
        code: 'FR-MQ',
        name: 'Martinique',
        role: 'secondary',
        projection: {
          id: 'mercator',
          family: 'CYLINDRICAL',
          parameters: {
            center: [
              -61.03,
              14.67,
            ],
            scaleMultiplier: 1.6,
          },
        },
        layout: {
          translateOffset: [
            -324,
            35,
          ],
          clipExtent: [
            [
              -0.14,
              0,
            ],
            [
              -0.0996,
              0.029,
            ],
          ],
        },
        bounds: [
          [
            -61.23,
            14.39,
          ],
          [
            -60.81,
            14.88,
          ],
        ],
      },
      {
        code: 'FR-GF',
        name: 'Guyane',
        role: 'secondary',
        projection: {
          id: 'mercator',
          family: 'CYLINDRICAL',
          parameters: {
            center: [
              -53.2,
              3.9,
            ],
            scaleMultiplier: 0.6,
          },
        },
        layout: {
          translateOffset: [
            -324,
            155,
          ],
          clipExtent: [
            [
              -0.14,
              0.029,
            ],
            [
              -0.0996,
              0.0864,
            ],
          ],
        },
        bounds: [
          [
            -54.6,
            2.1,
          ],
          [
            -51.6,
            5.8,
          ],
        ],
      },
      {
        code: 'FR-RE',
        name: 'La Réunion',
        role: 'secondary',
        projection: {
          id: 'mercator',
          family: 'CYLINDRICAL',
          parameters: {
            center: [
              55.52,
              -21.13,
            ],
            scaleMultiplier: 1.2,
          },
        },
        layout: {
          translateOffset: [
            313,
            -96,
          ],
          clipExtent: [
            [
              0.0967,
              -0.052,
            ],
            [
              0.1371,
              -0.02,
            ],
          ],
        },
        bounds: [
          [
            55.22,
            -21.39,
          ],
          [
            55.84,
            -20.87,
          ],
        ],
      },
      {
        code: 'FR-YT',
        name: 'Mayotte',
        role: 'secondary',
        projection: {
          id: 'mercator',
          family: 'CYLINDRICAL',
          parameters: {
            center: [
              45.16,
              -12.8,
            ],
            scaleMultiplier: 1.6,
          },
        },
        layout: {
          translateOffset: [
            316,
            -173,
          ],
          clipExtent: [
            [
              0.0967,
              -0.076,
            ],
            [
              0.1371,
              -0.052,
            ],
          ],
        },
        bounds: [
          [
            44.98,
            -13,
          ],
          [
            45.3,
            -12.64,
          ],
        ],
      },
      {
        code: 'FR-MF',
        name: 'Saint-Martin',
        role: 'secondary',
        projection: {
          id: 'mercator',
          family: 'CYLINDRICAL',
          parameters: {
            center: [
              -62.85,
              17.92,
            ],
            scaleMultiplier: 5,
          },
        },
        layout: {
          translateOffset: [
            -324,
            -119,
          ],
          clipExtent: [
            [
              -0.14,
              -0.052,
            ],
            [
              -0.0996,
              -0.032,
            ],
          ],
        },
        bounds: [
          [
            -63.15,
            18.04,
          ],
          [
            -63,
            18.13,
          ],
        ],
      },
      {
        code: 'FR-PM',
        name: 'Saint-Pierre-et-Miquelon',
        role: 'secondary',
        projection: {
          id: 'mercator',
          family: 'CYLINDRICAL',
          parameters: {
            center: [
              -56.23,
              46.93,
            ],
            scaleMultiplier: 1.3,
          },
        },
        layout: {
          translateOffset: [
            -324,
            -176,
          ],
          clipExtent: [
            [
              -0.14,
              -0.076,
            ],
            [
              -0.0996,
              -0.052,
            ],
          ],
        },
        bounds: [
          [
            -56.42,
            46.75,
          ],
          [
            -56.13,
            47.15,
          ],
        ],
      },
      {
        code: 'FR-WF',
        name: 'Wallis-et-Futuna',
        role: 'secondary',
        projection: {
          id: 'mercator',
          family: 'CYLINDRICAL',
          parameters: {
            center: [
              -178.1,
              -14.3,
            ],
            scaleMultiplier: 2.7,
          },
        },
        layout: {
          translateOffset: [
            313,
            59,
          ],
          clipExtent: [
            [
              0.0967,
              0.012,
            ],
            [
              0.1371,
              0.033,
            ],
          ],
        },
        bounds: [
          [
            -178.2,
            -14.4,
          ],
          [
            -176.1,
            -13.2,
          ],
        ],
      },
      {
        code: 'FR-PF',
        name: 'Polynésie française',
        role: 'secondary',
        projection: {
          id: 'mercator',
          family: 'CYLINDRICAL',
          parameters: {
            center: [
              -150.55,
              -17.11,
            ],
            scaleMultiplier: 0.5,
          },
        },
        layout: {
          translateOffset: [
            311,
            203,
          ],
          clipExtent: [
            [
              0.0967,
              0.06,
            ],
            [
              0.1371,
              0.0864,
            ],
          ],
        },
        bounds: [
          [
            -154,
            -28,
          ],
          [
            -134,
            -7,
          ],
        ],
      },
      {
        code: 'FR-PF-2',
        name: 'Polynésie française (îles éloignées)',
        role: 'secondary',
        projection: {
          id: 'mercator',
          family: 'CYLINDRICAL',
          parameters: {
            center: [
              -150.55,
              -17.11,
            ],
            scaleMultiplier: 0.06,
          },
        },
        layout: {
          translateOffset: [
            297,
            122,
          ],
          clipExtent: [
            [
              0.0967,
              0.033,
            ],
            [
              0.1371,
              0.06,
            ],
          ],
        },
        bounds: [
          [
            -154,
            -28,
          ],
          [
            -134,
            -7,
          ],
        ],
      },
      {
        code: 'FR-NC',
        name: 'Nouvelle-Calédonie',
        role: 'secondary',
        projection: {
          id: 'mercator',
          family: 'CYLINDRICAL',
          parameters: {
            center: [
              165.8,
              -21.07,
            ],
            scaleMultiplier: 0.3,
          },
        },
        layout: {
          translateOffset: [
            313,
            -13,
          ],
          clipExtent: [
            [
              0.0967,
              -0.02,
            ],
            [
              0.1371,
              0.012,
            ],
          ],
        },
        bounds: [
          [
            163,
            -22.7,
          ],
          [
            168,
            -19.5,
          ],
        ],
      },
    ],
  }

  // Step 3: Load the composite projection
  // Specify the target dimensions for the projection
  // Adjust width and height as needed for your use case
  const projection = loadCompositeProjection(config, {
    width: 960,
    height: 500,
    debug: true,
  })

  return projection
}
